package com.iteazer.forms;

import com.iteazer.client.Worker;

/**
 *
 * @author Wsl_F@ITeazer
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMAC = new javax.swing.JLabel();
        labelServer = new javax.swing.JLabel();
        buttonConnect = new javax.swing.JButton();
        buttonDisconnect = new javax.swing.JButton();
        labelRed = new javax.swing.JLabel();
        labelGreen = new javax.swing.JLabel();
        labelBlue = new javax.swing.JLabel();
        textMAC = new javax.swing.JTextField();
        textServer = new javax.swing.JTextField();
        textRed = new javax.swing.JTextField();
        textGreen = new javax.swing.JTextField();
        textBlue = new javax.swing.JTextField();
        buttonSetColor = new javax.swing.JButton();
        labelColor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaCommands = new javax.swing.JTextArea();
        buttonPerformCommands = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelMAC.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        labelMAC.setText("MAC:");

        labelServer.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        labelServer.setText("Server:");

        buttonConnect.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        buttonConnect.setText("Connect");
        buttonConnect.setPreferredSize(new java.awt.Dimension(110, 32));
        buttonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConnectActionPerformed(evt);
            }
        });

        buttonDisconnect.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        buttonDisconnect.setText("Disconnect");
        buttonDisconnect.setPreferredSize(new java.awt.Dimension(110, 32));
        buttonDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDisconnectActionPerformed(evt);
            }
        });

        labelRed.setFont(new java.awt.Font("FreeMono", 1, 20)); // NOI18N
        labelRed.setText("red:");
        labelRed.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelRed.setMaximumSize(new java.awt.Dimension(80, 30));
        labelRed.setMinimumSize(new java.awt.Dimension(80, 30));
        labelRed.setPreferredSize(new java.awt.Dimension(80, 30));

        labelGreen.setFont(new java.awt.Font("FreeMono", 1, 20)); // NOI18N
        labelGreen.setText("green:");
        labelGreen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelGreen.setMaximumSize(new java.awt.Dimension(80, 30));
        labelGreen.setMinimumSize(new java.awt.Dimension(80, 30));
        labelGreen.setPreferredSize(new java.awt.Dimension(80, 30));

        labelBlue.setFont(new java.awt.Font("FreeMono", 1, 20)); // NOI18N
        labelBlue.setText("blue:");
        labelBlue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelBlue.setMaximumSize(new java.awt.Dimension(80, 30));
        labelBlue.setMinimumSize(new java.awt.Dimension(80, 30));
        labelBlue.setPreferredSize(new java.awt.Dimension(80, 30));

        textMAC.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        textMAC.setText("F1:6F:DB:2B:3B:4F");

        textServer.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        textServer.setText("127.0.0.1:1337");

        textRed.setText("0");

        textGreen.setText("255");

        textBlue.setText("0");

        buttonSetColor.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        buttonSetColor.setText("Set color");
        buttonSetColor.setPreferredSize(new java.awt.Dimension(110, 32));
        buttonSetColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetColorActionPerformed(evt);
            }
        });

        labelColor.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        labelColor.setText("Color:");

        textAreaCommands.setColumns(20);
        textAreaCommands.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        textAreaCommands.setRows(5);
        jScrollPane1.setViewportView(textAreaCommands);

        buttonPerformCommands.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        buttonPerformCommands.setText("Perform commands");
        buttonPerformCommands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerformCommandsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelMAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textMAC, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(textServer)))
                    .addComponent(labelColor)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelGreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textRed, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textBlue, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textGreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonDisconnect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonConnect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buttonSetColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(buttonPerformCommands))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPerformCommands))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMAC)
                            .addComponent(textMAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelServer))
                        .addGap(25, 25, 25)
                        .addComponent(buttonConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDisconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelColor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSetColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String getServerAddress() {
        String serverAddress = textServer.getText();
        if (!serverAddress.startsWith("http://")) {
            serverAddress = "http://" + serverAddress;
        }
        return serverAddress;
    }

    private String getMACAddress() {
        return textMAC.getText();
    }

    int getColor(String text) {
        int color;
        try {
            color = Integer.valueOf(text);
        } catch (NumberFormatException ex) {
            System.err.println("Couldn't parse color: " + ex.getMessage());
            color = 0;
        }
        if (color < 0 || color > 255) {
            color = 0;
        }
        return color;
    }

    private void buttonSetColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetColorActionPerformed

        int red = getColor(textRed.getText());
        int green = getColor(textGreen.getText());
        int blue = getColor(textBlue.getText());

        String serverAddress = getServerAddress();
        String macAddress = getMACAddress();
        Worker.setColorOllie(serverAddress, macAddress, red, green, blue);

        textRed.setText(String.valueOf(red));
        textGreen.setText(String.valueOf(green));
        textBlue.setText(String.valueOf(blue));

    }//GEN-LAST:event_buttonSetColorActionPerformed

    private void buttonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConnectActionPerformed

        String serverAddress = getServerAddress();
        String macAddress = getMACAddress();
        Worker.connectToOllie(serverAddress, macAddress);

    }//GEN-LAST:event_buttonConnectActionPerformed

    private void buttonDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDisconnectActionPerformed

        String serverAddress = getServerAddress();
        String macAddress = getMACAddress();
        Worker.disconnectToOllie(serverAddress, macAddress);

    }//GEN-LAST:event_buttonDisconnectActionPerformed

    private void buttonPerformCommandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerformCommandsActionPerformed

        String serverAddress = getServerAddress();
        String macAddress = getMACAddress();
        String[] commands = textAreaCommands.getText().split("\\r?\\n");
        Worker.performCommandsOllie(serverAddress, macAddress, commands);

    }//GEN-LAST:event_buttonPerformCommandsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConnect;
    private javax.swing.JButton buttonDisconnect;
    private javax.swing.JButton buttonPerformCommands;
    private javax.swing.JButton buttonSetColor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBlue;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelGreen;
    private javax.swing.JLabel labelMAC;
    private javax.swing.JLabel labelRed;
    private javax.swing.JLabel labelServer;
    private javax.swing.JTextArea textAreaCommands;
    private javax.swing.JTextField textBlue;
    private javax.swing.JTextField textGreen;
    private javax.swing.JTextField textMAC;
    private javax.swing.JTextField textRed;
    private javax.swing.JTextField textServer;
    // End of variables declaration//GEN-END:variables
}
